language: python
sudo: false
matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.7
      env: TOXENV=flake8

cache: pip

install:
  - pip install -U pip setuptools
  - pip install tox-travis

script:
  - tox

deploy:
  provider: pypi
  user: pddg
  password:
    secure: lzv4GGwWSP+qAqvIW47jTixmvOgHfv9GR5FMsyYxAooal99Z9lnYRw1rVS9wdlQIBJnwKWS0HyOtiJLJDFxtcxjmsypePvTDoFmB2GOFitRdO0/uLsGjgUjTWt2ZHjrZWFzf15FVg5AXLA/TvXYWNb8BAQQwf+5ug4Z0Hyi44z+mI1tpRi/aToMr5lwLTVrmJIHL3toXMKejCKmKMUdtNGqYWbTGhosXFsx3O9H2oIiaXvPn3D4x+dMC16jNNwnrx3te4KoJLOHf4rykjbO0A6jjoJ33oNWeqrF6nKJiiEc+cL4Dz3ZZN77KAPgK+vPVzC+kbobxIsepJoK+Xx+WKFzuxL1upGBz+sGT4tuFld1PeWH2qEymoL8eE3aCn4+OfSNMAizQe9EMRwOTMY2NENgm1Pc2BEMi0gXvv6UAV1Om4pWnmpVua5GmzKjELqk+3AmcS5rkrN8S7zKTVkxajFAzft2hKqo9ZloO9Bx2cA457vIAkGiBzW8mKSkGGRfyjvUwBvdDlRDvorrMXLyNv5G1E7o2V58kMY+evkLHuGtS27kp+9fNIxn6wNofjeSHI9tIvYWBr0s0riY0weu0WOM+3/Hg3CuA4F7RTZhj0y4Pb3OJjUtGcdOddGWO8YbEyo8r7kutpEN9FSqOQS547ECdQ14FWO7rQaH9JocWl6Y=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: '3.7'
  skip_existing: true

notifications:
  email: false
