---
name: Test
on: [push, pull_request]

env:
  release_python_version: 3.8
  reviewdog_version: 0.10.0

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.release_python_version }}
      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: |
              ~/.cache/pip
              .venv
          key: ${{ runner.os }}-pip-${{ env.release_python_version }}-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ env.release_python_version }}-
      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -r requirements.dev.txt
      - name: Restore reviewdog if available
        id: reviewdogcache
        uses: actions/cache@v1
        with:
          path: ~/bin
          key: ${{ runner.os }}-reviewdog-${{ env.reviewdog_version }}
          restore-keys: |
            ${{ runner.os }}-reviewdog-${{ env.reviewdog_version }}
      - name: Setup reviewdog
        if: steps.reviewdogcache.outputs.cache-hit != 'true'
        run: |
          mkdir -p $HOME/bin && curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b $HOME/bin v${{ env.reviewdog_version }}
      - name: Run lint
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -o pipefail
          reporter=$(if [[ "${{ github.event_name }}" ==  "pull_request" ]]; then echo github-pr-review; else echo github-check; fi)
          flake8 . | $HOME/bin/reviewdog -f=pep8 -name="lint" -reporter=$reporter
  test:
    needs: lint
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python_version:
          - 3.5
          - 3.6
          - 3.7
          - 3.8
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install pipenv
        run: |
          python -m pip install -U pip setuptools wheel
      - if: startsWith(runner.os, 'Linux')
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            .venv
            .tox
          key: ${{ runner.os }}-pip-${{ matrix.python_version }}-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python_version }}-
      - if: startsWith(runner.os, 'macOS')
        uses: actions/cache@v2
        with:
          path: |
            ~/Library/Caches/pip
          key: ${{ runner.os }}-pip-${{ matrix.python_version }}-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python_version }}-
      - if: startsWith(runner.os, 'Windows')
        uses: actions/cache@v2
        with:
          path: |
            ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ matrix.python_version }}-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python_version }}-
      - name: Install dependencies
        run: |
          pip install -r requirements.dev.txt
        env:
          PIP_EXISTS_ACTION: i
      - name: Run test
        run: |
          pytest -v .
  assert-version:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Ensre that tag name starts with "v"
        run: |
          set -o pipefail
          echo "${GITHUB_REF#refs/tags/}" | grep -E "^v([0-9]\.?){3}"
      - name: Ensure that package version and tag version are same
        run: |
          set -o pipefail
          GIT_TAG=$(echo "${GITHUB_REF#refs/tags/}")
          PACKAGE_VER=$(cat uroboros/__init__.py| grep -Po "(?<=version = \").+(?=\")")
          test "$GIT_TAG" = "v$PACKAGE_VER"
  release-package:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: [assert-version, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.release_python_version }}
      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: |
              ~/.cache/pip
              .venv
          key: ${{ runner.os }}-pip-${{ env.release_python_version }}-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ env.release_python_version }}-
      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -r requirements.dev.txt
      - name: Build sdist package
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true

